import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { config } from 'dotenv';
import ExcelJS from 'exceljs';
import { parseJsonColumn } from './helpers.js';
config({ path: new URL('../.env.test', import.meta.url) });
const { app } = await import('../server/index.js');
const { pool } = await import('../server/db.js');

let server, base, cookie;

before(async () => {
  server = await new Promise((resolve) => {
    const s = app.listen(0, () => resolve(s));
  });
  base = `http://localhost:${server.address().port}`;

  const res = await fetch(`${base}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Origin: process.env.APP_ORIGIN },
    body: JSON.stringify({ email: 'test-admin@example.com', password: 'TestPass123' }),
  });
  cookie = res.headers.get('set-cookie').split(';')[0];
});

after(async () => {
  server.close();
  await pool.end();
});

test('GET /api/export.xlsx requires auth', async () => {
  const res = await fetch(`${base}/api/export.xlsx`);
  assert.equal(res.status, 401);
});

test('GET /api/export.xlsx rejects an unknown filter key', async () => {
  const res = await fetch(`${base}/api/export.xlsx?bogus=1`, { headers: { Cookie: cookie } });
  assert.equal(res.status, 400);
});

test('GET /api/export.xlsx returns a workbook with Thefts and Filters sheets', async () => {
  const res = await fetch(`${base}/api/export.xlsx?project=HTG`, { headers: { Cookie: cookie } });
  assert.equal(res.status, 200);
  assert.equal(res.headers.get('content-type'), 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  assert.match(res.headers.get('content-disposition'), /attachment; filename="theft-register-\d{8}-\d{4}\.xlsx"/);

  const buffer = Buffer.from(await res.arrayBuffer());
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  const theftsSheet = workbook.getWorksheet('Thefts');
  assert.ok(theftsSheet);
  assert.equal(theftsSheet.getRow(1).getCell(1).value, 'ID');

  const [[{ count }]] = await pool.query(`SELECT COUNT(*) AS count FROM thefts WHERE project = 'HTG'`);
  // header row + data rows + one bold totals row
  assert.equal(theftsSheet.rowCount, count + 2);

  const totalsRow = theftsSheet.getRow(theftsSheet.rowCount);
  assert.equal(totalsRow.font.bold, true);

  const filtersSheet = workbook.getWorksheet('Filters');
  assert.ok(filtersSheet);
  const rows = filtersSheet.getSheetValues().slice(1).map((r) => [r[1], r[2]]);
  const projectRow = rows.find((r) => r[0] === 'Project');
  assert.equal(projectRow[1], 'HTG');
  const generatedByRow = rows.find((r) => r[0] === 'Generated by');
  assert.equal(generatedByRow[1], 'Test Admin');
});

test('export is capped at 5000 rows and audited', async () => {
  const [[{ count: beforeCount }]] = await pool.query(`SELECT COUNT(*) AS count FROM audit_log WHERE action = 'export'`);

  const res = await fetch(`${base}/api/export.xlsx`, { headers: { Cookie: cookie } });
  assert.equal(res.status, 200);

  const [[{ count: auditCount }]] = await pool.query(`SELECT COUNT(*) AS count FROM audit_log WHERE action = 'export'`);
  assert.equal(auditCount, beforeCount + 1);

  const [[auditRow]] = await pool.query(
    `SELECT meta FROM audit_log WHERE action = 'export' ORDER BY id DESC LIMIT 1`
  );
  const meta = parseJsonColumn(auditRow.meta);
  assert.ok(meta.row_count <= 5000);
});
