import ExcelJS from 'exceljs';

const COLUMNS = [
  { header: 'ID', key: 'id' },
  { header: 'Project', key: 'project' },
  { header: 'Post Date', key: 'post_date' },
  { header: 'Theft Date', key: 'theft_date' },
  { header: 'Site ID', key: 'site_id' },
  { header: 'Site Name', key: 'site_name' },
  { header: 'Last Visit Date', key: 'last_visit_date' },
  { header: 'Item Stolen', key: 'item_stolen' },
  { header: 'Item Type', key: 'item_type' },
  { header: 'Unit', key: 'unit' },
  { header: 'Length', key: 'length' },
  { header: 'RH Before', key: 'rh_before' },
  { header: 'RH After', key: 'rh_after' },
  { header: 'Dipstick Before (cm)', key: 'dipstick_before_cm' },
  { header: 'Dipstick After (cm)', key: 'dipstick_after_cm' },
  { header: 'Probe Before (L)', key: 'probe_before_l' },
  { header: 'Probe After (L)', key: 'probe_after_l' },
  { header: 'Fuel Before (L)', key: 'fuel_before_l' },
  { header: 'Fuel After (L)', key: 'fuel_after_l' },
  { header: 'Quantity Lost', key: 'quantity_lost' },
  { header: 'Quantity Override', key: 'quantity_override' },
  { header: 'Quantity (NED)', key: 'quantity_ned' },
  { header: 'Quantity NED Override', key: 'quantity_ned_override' },
  { header: 'Unit Price (GHS)', key: 'unit_price' },
  { header: 'Price Override', key: 'price_override' },
  { header: 'Subtotal (GHS)', key: 'subtotal' },
  { header: 'Posted By', key: 'posted_by' },
  { header: 'Source', key: 'source_time' },
  { header: 'Source Msg IDs', key: 'source_msg_ids' },
  { header: 'Flags', key: 'flags' },
  { header: 'Remarks', key: 'remarks' },
  { header: 'Raw Post', key: 'raw_post' },
];

const DATE_KEYS = new Set(['post_date', 'theft_date', 'last_visit_date']);
const NUMBER_KEYS = new Set([
  'id',
  'rh_before',
  'rh_after',
  'dipstick_before_cm',
  'dipstick_after_cm',
  'probe_before_l',
  'probe_after_l',
  'fuel_before_l',
  'fuel_after_l',
  'quantity_lost',
  'quantity_ned',
  'unit_price',
  'subtotal',
]);
const BOOL_KEYS = new Set(['quantity_override', 'quantity_ned_override', 'price_override']);

function formatDate(isoDate) {
  if (!isoDate) return '';
  const [y, m, d] = isoDate.split('-');
  return `${d}/${m}/${y}`;
}

function formatDateTime(date) {
  const pad = (n) => String(n).padStart(2, '0');
  return `${pad(date.getDate())}/${pad(date.getMonth() + 1)}/${date.getFullYear()} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

// Every value goes through String(...) or Number(...) before being assigned, so a cell
// is always plain text or a number — never a formula, however the source data looks.
function cellValue(key, row) {
  const raw = row[key];
  if (raw === null || raw === undefined) return '';
  if (DATE_KEYS.has(key)) return formatDate(raw);
  if (NUMBER_KEYS.has(key)) return Number(raw);
  if (BOOL_KEYS.has(key)) return raw ? 'Yes' : 'No';
  return String(raw);
}

export function buildExportWorkbook({ rows, filters, generatedBy, generatedAt, fuelLostL, grandTotal }) {
  const workbook = new ExcelJS.Workbook();

  const sheet = workbook.addWorksheet('Thefts');
  sheet.columns = COLUMNS.map((c) => ({ header: c.header, key: c.key, width: 16 }));
  for (const row of rows) {
    const values = {};
    for (const c of COLUMNS) values[c.key] = cellValue(c.key, row);
    sheet.addRow(values);
  }

  const totalsRow = sheet.addRow({ item_stolen: 'Totals', quantity_lost: Number(fuelLostL) || 0, subtotal: Number(grandTotal) || 0 });
  totalsRow.font = { bold: true };

  const filtersSheet = workbook.addWorksheet('Filters');
  filtersSheet.columns = [
    { header: 'Field', key: 'field', width: 20 },
    { header: 'Value', key: 'value', width: 40 },
  ];
  const filterLabels = {
    project: 'Project',
    site_id: 'Site ID',
    from: 'From',
    to: 'To',
    item_type: 'Item type',
    flagged: 'Flagged only',
  };
  for (const [key, label] of Object.entries(filterLabels)) {
    filtersSheet.addRow({ field: label, value: filters[key] ? String(filters[key]) : 'All' });
  }
  filtersSheet.addRow({ field: 'Generated by', value: String(generatedBy) });
  filtersSheet.addRow({ field: 'Generated at', value: formatDateTime(generatedAt) });

  return workbook;
}

export function exportFileName(now = new Date()) {
  const pad = (n) => String(n).padStart(2, '0');
  const y = now.getFullYear();
  const m = pad(now.getMonth() + 1);
  const d = pad(now.getDate());
  const hh = pad(now.getHours());
  const mm = pad(now.getMinutes());
  return `theft-register-${y}${m}${d}-${hh}${mm}.xlsx`;
}
