import { useState, useEffect } from 'react';
import { apiFetch } from '../api.js';
import { toQuery } from '../TheftsDataContext.jsx';
import { formatMoney, formatDate } from '../format.js';
import Cards from './Cards.jsx';
import MonthlyChart from './MonthlyChart.jsx';

const FILTER_LABELS = {
  project: 'Project',
  site_id: 'Site ID',
  from: 'From',
  to: 'To',
  item_type: 'Item type',
  flagged: 'Flagged only',
};

// All filtered rows (no raw_post, no pagination) for print/PDF — separate from the
// Datasheet's paginated table since a print report always needs the full set.
export default function PrintReport({ filters, summary, user, onClose }) {
  const [rows, setRows] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    apiFetch(`/thefts?${toQuery(filters, { all: 1 })}`)
      .then((res) => setRows(res.rows))
      .catch((e) => setError(e.message));
  }, [filters]);

  const generatedAt = new Date().toLocaleString('en-GB');

  return (
    <div className="print-report">
      <div className="print-report-toolbar no-print">
        <button onClick={() => window.print()}>Print</button>
        <button onClick={onClose}>Close</button>
      </div>

      <h1>Theft Register — Report</h1>
      <div className="print-meta">
        <div>
          {Object.entries(FILTER_LABELS).map(([key, label]) => (
            <span key={key} className="print-filter">
              {label}: {filters[key] ? String(filters[key]) : 'All'}
            </span>
          ))}
        </div>
        <div>
          Generated by {user.name} at {generatedAt}
        </div>
      </div>

      {summary && <Cards summary={summary} />}
      {summary && <MonthlyChart data={summary.by_month} />}

      {error && <div className="error-banner">{error}</div>}
      {!rows && !error && <div className="loading">Loading…</div>}
      {rows && (
        <table className="print-table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Project</th>
              <th>Site</th>
              <th>Item</th>
              <th>Type</th>
              <th>Qty</th>
              <th>Qty (NED)</th>
              <th>Unit price</th>
              <th>Subtotal</th>
              <th>Flags</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.id} className={r.flags ? 'flagged' : ''}>
                <td>{formatDate(r.post_date)}</td>
                <td>{r.project}</td>
                <td>{r.site_name || r.site_id || '—'}</td>
                <td>{r.item_stolen}</td>
                <td>{r.item_type}</td>
                <td>
                  {r.quantity_lost ?? '—'} {r.unit !== '-' ? r.unit : ''}
                </td>
                <td>
                  {r.quantity_ned ?? '—'} {r.unit !== '-' ? r.unit : ''}
                </td>
                <td>{formatMoney(r.unit_price)}</td>
                <td>{formatMoney(r.subtotal)}</td>
                <td>{r.flags || ''}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
